version: '3'
services:

  lib-api-db:
    image: 'postgres:14'
    container_name: 'lib-api-db'
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=omegalul'
      - 'POSTGRES_PASSWORD=newpassword'
      - 'POSTGRES_DB=lib-api-db'


  lib-service-db:
    image: 'postgres:14'
    container_name: 'lib-service-db'
    ports:
      - '5435:5432'
    environment:
      - 'POSTGRES_USER=omegalul'
      - 'POSTGRES_PASSWORD=newpassword'
      - 'POSTGRES_DB=lib-service-db'

  lib-api:
    image: omegalul123/lib-api
    container_name: lib-api
    links:
      - kafka
      - lib-api-db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://lib-api-db:5432/lib-api-db'
      - 'SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092'


  lib-service:
    image: omegalul123/lib-service
    container_name: lib-service
    links:
      - kafka
      - lib-service-db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://lib-service-db:5432/lib-service-db'
      - 'SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092'



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
        - zookeeper
    ports:
        - "9092:9092"
        - "9997:9997"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_JMX_PORT: 9997
        KAFKA_JMX_HOSTNAME: kafka


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      bootstrapservers: "PLAINTEXT://localhost:9092"